version: "3.8"

volumes:

  mongodb_data:
    external: true
    name: ${VW_VOLUME_MONGODB_ID}

  elastic_data:
    external: true
    name: ${VW_VOLUME_ELASTIC_ID}

services:

  # MongoDB database service
  mongodb:
    image: mvertes/alpine-mongo:4.0.6-1
    volumes:
      - mongodb_data:/data/db
    #restart: on-failure # make this container restart on failure

  # Elasticsearch search server service
  elastic:
    image: blacktop/elasticsearch:7.9.2
    volumes:
      - elastic_data:/usr/share/elasticsearch/data
    #restart: on-failure # make this container restart on failure

  # the actual VedaWeb application, built based on Dockerfile
  app:
    build: .
    #restart: on-failure # make this container restart on failure
    ports:
      - "${VW_WEBAPP_HOST_PORT}:8080" # the application will be served via the host port set in .env
    depends_on:
      - mongodb
      - elastic